# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
pool:
  vmImage: ubuntu-latest

trigger:
  batch: true
  branches:
    include:
      - master
      - refs/pull/*
      - refs/tags/release-*

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- powershell: |
   $ver = $env:BUILD_SOURCEBRANCH.remove(0, 10)
   Write-Host "##vso[task.setvariable variable=Version]$ver"
   Write-host $(Build.SourceVersion)
   Write-host $(Build.BuildNumber)
   Write-host $(Build.SOURCEBRANCH)
   Get-ChildItem env:
  displayName: 'Update version to Tag'


- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
