# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
pool:
  vmImage: ubuntu-latest

trigger:
  batch: true
  branches:
    include:
      - master
      - refs/pull/*
      - refs/tags/release-*

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- powershell: |
    $ver = ($(Build.SOURCEBRANCHNAME)).TrimStart('release-')
    Write-Host "##vso[task.setvariable variable=Version]$ver"
  displayName: 'Get release version'
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/release-'))


- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
