# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
pool:
  vmImage: ubuntu-latest

trigger:
  batch: true
  branches:
    include:
      - master
      - refs/pull/*
      - refs/tags/release-*

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      pwd
      Invoke-WebRequest -Uri 'https://dotalignartifacts.blob.core.windows.net/releasebinaries/falcon/Falcon_7.8.4.zip' -OutFile falcon_latest.zip
      ls -la
- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: '**/falcon_latest.zip'
    destinationFolder: 'falcon_app'
    cleanDestinationFolder: true
    overwriteExistingFiles: true
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      sudo sh -c ''echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-$(lsb_release -cs)-prod $(lsb_release -cs) main" > /etc/apt/sources.list.d/dotnetdev.list''
      sudo apt-get update
      sudo apt-get install azure-functions-core-tools-4

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      cd 'falcon_app'
      func init --worker-runtime dotnet --docker
- task: Docker@2
  inputs:
    containerRegistry: 'arc2'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
